language: node_js
node_js:
    - "node"
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y ruby
    - npm install -g grunt-cli
    - npm install grunt@0.4.1
    - npm install grunt-contrib-sass@0.7.4
    - npm install grunt-contrib-watch@1.0.0
    - gem install compass
install:
    - npm install
before_script:
